---
- name: Install python3-debian for Deb822 repository management
  ansible.builtin.apt:
    name: python3-debian
    state: present

- name: Configure Docker APT repository
  ansible.builtin.deb822_repository:
    name: docker
    types:
      - deb
    uris:
      - https://download.docker.com/linux/ubuntu
    suites:
       - "{{ ansible_facts['distribution_release'] }}"
    components:
      - stable
    architectures:
      - amd64
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    state: present
    enabled: true

- name: Refresh APT cache after adding Docker repository
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker Engine packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-docker
    state: present

- name: Ensure Docker service is enabled and running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
