[swarm_managers]
platform-node-01 ansible_host=68.183.95.65 ansible_python_interpreter=/usr/bin/python3 swarm_advertise_addr=10.10.10.3

[swarm_workers]
platform-node-02 ansible_host=165.232.183.128 ansible_python_interpreter=/usr/bin/python3 swarm_advertise_addr=10.10.10.2

[platform_nodes:children]
swarm_managers
swarm_workers
