[swarm_managers]
platform-node-01 ansible_host=143.244.137.34 ansible_python_interpreter=/usr/bin/python3 swarm_advertise_addr=10.10.10.2

[swarm_workers]
platform-node-02 ansible_host=64.227.156.190 ansible_python_interpreter=/usr/bin/python3 swarm_advertise_addr=10.10.10.3

[platform_nodes:children]
swarm_managers
swarm_workers
