[swarm_managers]
platform-node-01 ansible_host=64.227.184.141 ansible_user=platform ansible_python_interpreter=/usr/bin/python3 swarm_advertise_addr=10.10.10.2

[swarm_workers]

[platform_nodes:children]
swarm_managers
swarm_workers
