apiVersion: v1
kind: Pod

metadata:
  name: lab-web
  labels:
    app: lab-web

spec:
  imagePullSecrets:
    - name: ghcr-pull

  containers:
    - name: lab-web
      image: ghcr.io/alirasheedmd/platform-lab-web:v1.1.0
      ports:
        - containerPort: 80
