events {}

http {
    upstream lab_backend {
        server lab-web:80;
    }

    server {
        listen 80 default_server;
        server_name _;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl default_server;
        server_name _;

        ssl_certificate     /etc/nginx/tls.crt;
        ssl_certificate_key /run/secrets/tls.key;

        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://lab_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}

